name: deploy-javadoc
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  gen-and-deploy-javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repo
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
          java-package: jdk+fx
      - name: Create javadoc folder
        run: mkdir javadoc
      - name: Generate Javadoc
        working-directory: javadoc
        run: javadoc -private -sourcepath ../src/{**/,**/**/}*.java
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: javadoc
